### PR TITLE
HA 0.106.x compatible

### PR DESCRIPTION
**Pull request by Lau-ie**
Added two lines of code to the main file:
setConfig(config) {
  config = JSON.parse(JSON.stringify(config)); // This uses built-in functions, but may be slower than

Based on Thomas Loven's helpfull comment.

Confirmed working on my install

### CODE REVIEW

**Comment by r-renato** [comment]
Hi, for me this working fine even if it introduces a rendering issues when the plugin is used in sequence with other card type.
Practically, while the other cards are rendered the flex-horseshoe-card not. To show all cards I must to refresh the page over and over again.

**Comment by HFsi** [comment]
Doesn't work on 0.106.6

**Comment by noodlemctwoodle** [comment]
Confirmed working on 106.6 with changes suggested by @Lau-ie.

**Comment by HFsi** [comment]
In which part of the code should I add those lines?

**Comment by noodlemctwoodle** [comment]
@HFsi  

# Steps to get working:
 1. Download  [flex-horseshoe-card.js](https://github.com/Lau-ie/flex-horseshoe-card/blob/master/flex-horseshoe-card.js) from Lau-ei as they have already made the required changes
 2. Put `flex-horseshoe-card.js` in a a folder by itself and remove any other files such as *.js.gz

    image
 3. Reboot Home Assistant
 4. Use the updated docs that are on either Lau-ei GitHub [fork](https://github.com/Lau-ie/flex-horseshoe-card) or My GitHub [fork](https://github.com/noodlemctwoodle/flex-horseshoe-card)

**Comment by riddik14** [comment]
I have add this repo in hacs 

https://github.com/Lau-ie/flex-horseshoe-card

I have reinstalled the plugin from hacs and it work now.

thank you  Lau-ie

**Comment by HFsi** [comment]
Yep, it's working now!

**Comment by AmoebeLabs** [comment]
Hi everyone!

I'm slowly recovering from almost a year of illness, so that's the reason I didn't respond for a long time.
I'm still running hass 0.98, so I also have to update that part of my domotica installation.

I will test new version first, and then release a new version for HACS!

**Comment by Lau-ie** [comment]
Hi Amoebelabs!

Very glad to have you back too further develop this awesome card!

**Comment by AmoebeLabs** [comment]
> Hi Amoebelabs!
> 
> Very glad to have you back too further develop this awesome card!

Thanx for your PR btw, it helped a lot of ppl while I was not able to do any work on this.

I have now deployed another hass container next to my old 0.98 container, and since I'm using MQTT for most of my sensors, I can rebuild the new hass next to the old hass.

A lot has changed I must say:

- My themes don't work anymore
- Some cards are deprecated
- The horseshoe has a 0.110 incompatibility (icon size, fixed already locally)
- My other still unreleased card doesn't work anymore...
- The order of events for custom cards seems to have changed, sometimes the horseshoe and the new card are fully drawn after a data update in the new hass, where they are fully drawn when the view is selected in the old hass. Must look into that later.

So, enough to do.

I will post on the forum once I tested and made a new release.

**Pull request merged**
